name: Daily News Scraper

on:
  workflow_dispatch:   # manual trigger
  schedule:
    - cron: "0 3 * * *"   # runs every day at 03:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run news scraper
        run: |
          python news_scraper.py <<EOF
          Reliance
          01-11-2016
          31-12-2016
          EOF

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: news-data
          path: news_results.csv
